### ISSUE TITLE
for exported fn, verus should check if pre/post-conditions are well-formed in export

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/verus#101]
currently, verus generates malformed air code if a pre-condition or post-condition references a fn which isn't public. it should generate a useful error message instead.

**Comment by utaal** [comment]
Would you be up for picking up this as a task? I think there's a fairly natural place for this in https://github.com/secure-foundations/verus/blob/main/source/vir/src/well_formed.rs

**Comment by tjhance** [comment]
chris fixed in 27a3c5c1dc5c77c2c239d18e6095adbff5e84b65
