### ISSUE TITLE
Panic when external items are referenced in verified code

### ISSUE THREAD

**Issue by matthias-brun** [secure-foundations/verus#143]
This code verifies fine:

```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;
use pervasive::vec::*;

fn f(s: Vec<u64>) { }

fn main() {}
```

But if the `vec` import is missing, the verifier panics:

```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;

fn f(s: Vec<u64>) { }

fn main() {}
```

```
fhs m: source ν ./tools/rust-verify.sh /st/verus/panic.rs
Verifying root module
thread 'rustc' panicked at 'no entry found for key', vir/src/poly.rs:151:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'valid Mutex for verifier: PoisonError { .. }', /home/m/verus/source/rust_verify/src/driver.rs:120:10
```

This isn't specific to `Vec`, the same happens for other imports.

**Comment by utaal** [comment]
I think the general issue here is that we panic when types from external crates are referenced. Maybe we should catch that early (until we have multi-crate support).

The `Vec` when the import from pervasive is missing ends up being `std::vec::Vec` from crate std, for which we don't have the hir.

**Comment by utaal** [comment]
https://github.com/secure-foundations/verus/commit/ba9c0ca3580a763ca1ff98ec47519ae3a343c060 is probably only a partial fix.

**Comment by utaal** [comment]
I think we should have added a guard for most/all places where this could panic. Feel free to reopen if this happens again.
