### ISSUE TITLE
How to build exec code with cargo outside verus

### ISSUE THREAD

**Issue by marshtompsxd** [secure-foundations/verus#175]
Hi Verus team, I was trying to build my project with verus. The project structure is like
```
├── Cargo.lock
├── Cargo.toml
└── src
    ├── logic.rs
    └── main.rs
```
and it sits outside verus folder.

The `logic.rs` imports some files from verus:
```
#[allow(unused_imports)]
use builtin_macros::*;
#[allow(unused_imports)]
use builtin::*;

mod pervasive;
#[allow(unused_imports)]
use pervasive::{*, option::Option, map::*};
```
and is successfully verified by `./tools/rust-verify.sh ../../myproject/src/logic.rs`

I imported `builtin_macros` and `builtin` in my cargo.toml
```
builtin_macros = { path = "../verus/source/builtin_macros" }
builtin = { path = "../verus/source/builtin" }
```
However, I was not able to import pervasive. 

I have tried the following:
1. import pervasive in cargo.toml -- it does not work because there is no cargo.toml in the pervasive folder
2. copy `verus/source/pervasive` to `myproject/src/pervasive` -- it does not work and report
```
error[E0583]: file not found for module `pervasive`
 --> src/logic.rs:9:1
  |
9 | mod pervasive;
  | ^^^^^^^^^^^^^^
  |
  = help: to create the module `pervasive`, create file "src/logic/pervasive.rs" or "src/logic/pervasive/mod.rs"
```
3. move `myproject/src/pervasive` to `myproject/src/logic/pervasive` -- a lot of errors are reported like
```
error[E0531]: cannot find tuple struct or tuple variant `Proof` in this scope
   --> src/logic/pervasive/atomic.rs:127:17
    |
127 |             let Proof(t) = exec_proof_from_false();
    |                 ^^^^^ not found in this scope
...
493 | make_signed_integer_atomic!(PAtomicI64, PermissionI64, AtomicI64, i64, wrapping_add_i64, wrapping_sub_i64, -0x8000_0000_0000_0000, 0x7fff_ffff_ffff_fff...
    | --------------------------------------------------------------------------------------------------------------------------------------------------------- in this macro invocation
```

I also looked into https://github.com/utaal/verified-nrkernel/tree/main/page-table but didn't find out how to build exec code with cargo there.

Could you please let me know what is the best practice to organize and build (using cargo) projects that rely on verus but sit outside verus?

**Comment by utaal** [comment]
Hi @marshtompsxd; due to the fact that verus extends rust with custom syntax, the custom `pervasive` library (and currently, some custom type-checking rules) it isn't possible to build exec code outside of verus; among other things the `#[spec]` and `#[proof]` code needs to be erased before compilation: a regular `rustc` doesn't understand how to do that.

This may become possible in the near future, but for now the verified crate needs to be at the root of your project and -- if you depend on additional external crates -- you'll need to pass them to rustc manually (as `cargo` will probably fail currently).

The `page-table` project you looked at doesn't really have any runnable code yet :)

**Comment by tjhance** [comment]
As a workaround, you can run erasure to extract ordinary rust code. See the `--compile` and `--print-erased` options.

**Comment by utaal** [comment]
I'm not super-sure the rustc emitter behind `--print-erased` guarantees valid rust code (it's definitely intended for debug purposes only), but that may work.

We've discussed offline possible strategies, but they may hold off until we move to mainline rustc and macro-based syntax, which may simplify things.
