### ISSUE TITLE
Clarification on #[verifier(publish)]

### ISSUE THREAD

**Issue by marshtompsxd** [secure-foundations/verus#183]
Hi Verus team, I was writing some spec predicates like
```
pub struct ClusterState {
    ...
}

impl ClusterState {
    #[spec]
    pub fn empty(&self) -> bool {
        ... // check some fields in self
    }

    #[spec]
    pub fn well_formed(&self) -> bool {
        ... // check some fields in self
    }

    #[spec]
    pub fn trivially_true(&self) -> bool {
        true
    }
}
```
and I find that both `empty` and `well_formed` are always evaluated as false if I call them in **another rust file**, while `trivially_true` is sometimes true and sometimes false.

I find that `#[verifier(publish)]` is used in pervasive and guess that this might help. After adding this macro to each predicate they start to work properly in different rust files.

I am just wondering what is exactly the meaning of `#[verifier(publish)]`? And what will happen if we do not have this macro for a spec function?

**Comment by tjhance** [comment]
`publish` means that the definition of the function will be visible to proofs defined in other modules. (Note that this is stronger than being `pub`, which only means that the function's name and signature are visible, as in ordinary Rust.) If the definition isn't visible, then other modules will treat the function as uninterpreted, meaning they can only reason about the function via lemmas exported by that module.

If you use the new syntax, `publish` has been replaced by `open`. Also in the new syntax, the user is required to explicitly mark any `pub` function as `open` or `closed` - our hope is that it will minimize this kind of confusion.
