### ISSUE TITLE
Casting results in wrong output type emitted in air

### ISSUE THREAD

**Issue by isubasinghe** [secure-foundations/verus#184]
Currently equality is only present for primitive types it seems, to get around this limitation I decided to represent an enum as u64 and simply cast as a u64 when needed. Unfortunately this results in a panic as the wrong air type is emitted, in this case "Colour" was emitted.

```rust
#[derive(Eq, PartialEq, Copy, Clone)]
#[repr(u64)]
pub enum Colour {
    Red = 1, 
    White = 2, 
    Blue = 3
}

spec fn below(c: Colour, d: Colour) -> bool {
    let c = c as u64;
    let d = d as u64;
    let red = Colour::Red as u64;
    let blue = Colour::Blue as u64;

    c == red || c == d || d == blue
}

```
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/28187128/176857948-60a68025-eae2-4baf-90fa-3fd22f9846b7.png">

I got around this limitation by having external_body functions that handled the conversion for me, but thought that I should perhaps note this issue.

**Comment by tjhance** [comment]
Hi!

To compare equality in spec code you can use `equal(a, b)` or (if you're using the new syntax) `a === b`. 

Currently, as you've noted, our encoding doesn't handle the cast from an enum to an int. We could fix it to have a nicer error message though.

**Comment by isubasinghe** [comment]
Thanks @tjhance, I shall use equal then, I shall close this issue in that case.
