### ISSUE TITLE
vir::def::path_to_string is not injective

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/verus#21]
vir::def::path_to_string is not injective, for example:

krate: Some("a"), segments: ["b"]

and

krate: None, segments: ["a", "b"]

will generate the same string. We need to adjust the encoding so that a krate prefix is distinguished.

**Comment by tjhance** [comment]
I think this was fixed in 43f308508b2ea5e2ccaa8c3f4fb44bc344b27b6f

@Chris-Hawblitzel can you confirm?

**Comment by Chris-Hawblitzel** [comment]
Oops ... I forgot to close the issue.  Yes, it was fixed.
