### ISSUE TITLE
default command line options for testing  (`multiple-errors`)

### ISSUE THREAD

**Issue by channy412** [secure-foundations/verus#256]
I found that `multiple-errors` was set to 0 when I am running `cargo test` on my machine,  while the default value is 2 when running Verus.  (https://github.com/secure-foundations/verus/blob/main/source/rust_verify/tests/common/mod.rs#L126) 
This changes behavior around `air_context.check_valid_again`, which is about Verus trying to find earlier error locations. 
I am not sure if this is intended but it might introduce some discrepancies.

**Comment by utaal** [comment]
This was intentional: we only want one failure in tests so we can check it’s the one we expect. We shouldn’t check_valid_again in tests for the purpose of finding other failures.
(If you need different behavior for goal splitting, consider restructuring that logic while preserving this behavior)

**Comment by channy412** [comment]
Ah, I see. It indeed makes sense to set the `multiple-errors` to 0 for test environments. Thanks for the clarification!
