### ISSUE TITLE
verus doesn't handle negative integer literals properly

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/verus#47]
For example, Verus currently encodes the `i64` value `-0x8000_0000_0000_0000` as:

```
(- 0 (iClip 64 9223372036854775808)
```

**Comment by Chris-Hawblitzel** [comment]
Signed integer literals weren't implemented yet, so by default it was treating them all as mostly uninterpreted.  Commit 3f88a47be84be09dbdafe5d4e53357a02a9cec65 implements them.
