### ISSUE TITLE
Different SMT files over executions of Verus - different trigger ordering, different number of check-sat

### ISSUE THREAD

**Issue by channy412** [secure-foundations/verus#68]
This GC example( f78bfcb81caaf1db6712ac52de905085f749d628 ) is about using a 32-bit integer as an array of 16 elements. When I uncomment lines from 147 to 152, the verification result becomes unstable. Yi and I were looking into this example and found that Verus generates two different SMT files over separate runs. These SMT files have some different ordering of triggers and a different number of `check-sat`. 
To be specific, in `log_fail.smt` file, when I manually flip the order of these two triggers(to make the ordering the same as in `log_success.smt`), Z3 suddenly returns `unsat` instead of `unknown`.
```
:pattern ((get_bit.? (I bv2@) loc2$))      ;; line 1971
:pattern ((get_bit.? (I bv@) loc2$))        
```
Also, `log_fail.smt` has one more `check-sat`. Here is the `diff` of that part.
```
<   (get-model)                                        ;; line 2303
<   (assert
<    (not %%location_label%%0)
<   )
<   (assert
<    %%query%%
<   )
<   (set-option :rlimit 0)
<   (check-sat)
<   (set-option :rlimit 0)
```

Unmodified SMT files are `log_success.smt` and `log_fail.smt` 
[log_fail.txt](https://github.com/secure-foundations/verus/files/8111228/log_fail.txt)
[log_success.txt](https://github.com/secure-foundations/verus/files/8111229/log_success.txt)

I will try to make small examples that reproduce these two issues(different trigger ordering and a different number of `check-sat`) separately.

**Comment by Chris-Hawblitzel** [comment]
Does https://github.com/secure-foundations/verus/commit/b95fff1cd3c2af6386a172098a1f9055b0e77ead eliminate the different trigger orderings?

**Comment by channy412** [comment]
Yes, the above example now produces the same SMT file every time(over 50 runs). Thanks!

**Comment by channy412** [comment]
If I remember correctly, the different number of `check-sat` was due to the Verus' additional effort when it faces verification failure. In the above example, a particular trigger ordering made verification fail, and the failure lead to a different number of `check-sat`.
