### ISSUE TITLE
`vector` and `seq` in pervasive : failing trigger for vector `set`'s properties and a trivial unsoundness bug 

### ISSUE THREAD

**Issue by channy412** [secure-foundations/verus#83]
1. After calling `set` in prevasive/vec.rs(https://github.com/secure-foundations/verus/blob/main/source/pervasive/vec.rs#L28) , the below commented three properties are discovered through triggers in seq.rs(https://github.com/secure-foundations/verus/blob/main/source/pervasive/seq.rs#L93). During working on the bit-map example(https://github.com/secure-foundations/verus/commit/445c6cede6f3949bbe162c2af5ec63e07bfe54f3#diff-615c3ebc3c82354316137c5cbc27e219b3aca3447ea9ecfdc315b2f062d7c01dR123), I had to manually call one of those seq axioms. I wonder if it makes sense to add those properties as an axiom for vector's `set` function(as shown as below).

```
    #[verifier(external_body)]
    pub fn set(self, i: usize, a: A) -> Vec<A> {
        requires(i < self.view().len());
        ensures(|v2: Vec<A>| [
            equal(v2.view(), self.view().update(i, a)),
            // adding below three lines?
            //(1) self.len() == v2.len(),
            //(2) equal(v2.view().index(i), a),
            //(3) forall(|i2: int| i2 != i && i2 < self.view().len() >>= equal(v2.view().index(i2),self.view().index(i2))),
        ]);

        let mut v2 = self;
        v2.vec[i] = a;
        v2
    }
```
     

2. In the following function in seq.rs, `i1 != i2,` should be added in `requires`. Found this after suspiciously succeeding proof.
https://github.com/secure-foundations/verus/blob/main/source/pervasive/seq.rs#L112-L123

**Comment by Chris-Hawblitzel** [comment]
Thanks for finding the bug in axiom_seq_update_different.  It's fixed now in https://github.com/secure-foundations/verus/commit/ad70e2191ec6d593dbc3bd818669ea46da2f0d26 .

**Comment by Chris-Hawblitzel** [comment]
The incompleteness (1) is not caused by the triggers, which are firing as they should, but rather by the bit vector operations producing results that potentially don't satisfy has_type for the corresponding integer types.  To fix this, the bit vector operations just need axioms that say the results are in the range for the corresponding integer types (or they need to use clip).

**Comment by channy412** [comment]
Thanks a lot for the comments!  I updated bit-vector operations using `uclip` and `iclip` (7a9dacf25b6188890e59998aabbced76b40750a0) , and `seq` triggers work very well now.
