### ISSUE TITLE
Minor logging issue: `--log-vir` for `example/atomics.rs` and `example/og_counter.rs` panics

### ISSUE THREAD

**Issue by channy412** [secure-foundations/verus#89]
When I run `tools/rust-verify.sh rust_verify/example/atomics.rs  --log-vir logs/log.vir`, it gives `thread 'rustc' panicked at 'invalid atom ","', /Users/chanhee/.cargo/registry/src/github.com-1ecc6299db9ec823/sise-0.6.0/src/spaced_string_writer.rs:194:9`

Similarly, it makes the following run  `VERIFY_LOG_IR_PATH="logs" RUSTC=../rust/install/bin/rustc ../rust/install/bin/cargo test -p rust_verify --test atomics` hangs.

**Comment by tjhance** [comment]
fixed by ac1ecb65ecc9746c6030ecfb95648f1c0f8ba42e
